# Generated by Django 5.1.7 on 2025-03-31 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
                ('content', models.TextField(verbose_name='Content')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='Name')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
