# Generated by Django 5.1.7 on 2025-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
    ]
