# Generated by Django 5.1.7 on 2025-05-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_alter_comment_photo_alter_question_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
    ]
