# Generated by Django 5.1.7 on 2025-05-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
                ('language', models.IntegerField(choices=[(1, 'KOR'), (2, 'ENG'), (3, 'JPN'), (4, 'CHN')])),
            ],
        ),
    ]
