# Generated by Django 5.1.7 on 2025-05-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
